### PR TITLE
Simple shipping costs calculation

### PR DESCRIPTION
**Pull request by uo277776**
Hey, I've finished implementing a simple version of the shipping cost calculation. It allows the user to enter their address and calculates the distance with our "warehouse". The price is computed with a fixed value for each km. It is very simple but is a good point to implement the solid pods and the api of the carriers.

Maybe something can be improved, or extract the functions for computing the cost to another file to keep the code cleaner. What do you think?

### CODE REVIEW

**Comment by uo277776** [comment]
Hi guys! I just realised that the API I chose does not support https, so these may cause a security problem, you can see that the sonarcloud fails because of this problem. I will change the API tomorrow, I have found another free one that supports https.

**Comment by angelip2303** [comment]
Perfect using a more secure one will be better. The rest of it seems just fine!

**Comment by uo277776** [comment]
Hi! I changed the geocoding API to another one to support HTTPS and I also use the BingMaps API to show a map with the route.

Take a look and if you can try the shipping cost calculation to check if everything works well for you would be perfect.

**Comment by uo271580** [comment]
Wow, nice work. Really awesome having the map. I guess price computing should change since it is quite expensive, but the communication with the API looks great.

**Pull request merged**
