### PR TITLE
Sections 4.1 and 4.2 of Solution strategy added

### PR DESCRIPTION
**Pull request by LorenzoLaRocca**
Hi Pablo! I just finishing writing Sections 4.1 and 4.2 of the Solution Strategy section. Please review it and let me know if I missed something or there is something to modify. Have a nice evening! 
I am gonna check your section as soon as I can!

### CODE REVIEW

**Comment by uo271580** [comment]
I think in the first part you can remove typescript since it is not really a technology, more the support language. Also i think in the second part you could add other tools we use for creating the diagrams (ask to the other members). Else is okay

**Comment by LorenzoLaRocca** [comment]
Hey! Yes you are right for the first part, going to fix it. About the second maybe we should discuss is at the meeting because I am not sure what you want to use or if you have a tool that you are already familiar with, but I am going to ask anyway.

**Comment by LorenzoLaRocca** [comment]
Hi @uo271580 I modified the document and ready for review! let me know when you can. Have a nice weekend!

**Comment by LorenzoLaRocca** [comment]
Not to merge.

**Pull request closed without merging**
